### ISSUE TITLE
Add pv list

### ISSUE THREAD

**Issue by tonobo** [nak3/go-lvm#1]
Is there any possibility to call `C.lvm_list_pvs`, i always get an empty array?
After opening a vg handle the list will by empty and produces an segfault. `&lvm._Ctype_struct_dm_list{n:(*lvm._Ctype_struct_dm_list)(nil), p:(*lvm._Ctype_struct_dm_list)(nil)}`

**Comment by nak3** [comment]
Hi @tonobo, Thank you for interested in this project. But, there is a bad news... 2 month ago, while I was developping this library, upstream announced that `lvm2app.h` is deprecated.

https://sourceware.org/git/?p=lvm2.git;a=blob;f=liblvm/lvm2app.h;h=f64262d3283312b70510958558e0df8a30b8a545;hb=HEAD#l21

~~~
21 #warning "liblvm2app is deprecated, use D-Bus API instead."
~~~

Also, please refer to https://bugzilla.redhat.com/show_bug.cgi?id=1494598

This project(go-lvm) totally depends on `liblvm2app.h`, so I think that it is better not to use this library...

**Comment by tonobo** [comment]
Thanks a lot, i'll take a look at dbus api.

**Comment by tonobo** [comment]
FYI, I started writing a go lvm client against dbus. See [hetzneronline/go-lvm](https://github.com/hetzneronline/go-lvm)

**Comment by nak3** [comment]
Great. Thank you for sharing!
